In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_csv("F:\ML Practice\Project\creditcard.csv")

In [5]:
df

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [6]:
#Data Frame Informations

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [7]:
#Removeing Null values

df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
# distribution of True transactions & Fraud transactions

df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [9]:
True_Trans = df[df.Class == 0]
Fraud_Trans = df[df.Class == 1]

In [10]:
True_Trans.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [11]:
Fraud_Trans.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [12]:
#Finding Average amount of value for True and Fraud Transaction

df.groupby('Class').Amount.mean()

Class
0     88.291022
1    122.211321
Name: Amount, dtype: float64

In [13]:
# True Transaction is More Higher than Fradulant Trans SO we are going balancing the Dataset here.

True_Trans_sample = True_Trans.sample(n=492)

In [14]:
New_df = pd.concat([True_Trans_sample, Fraud_Trans], axis=0 )

In [15]:
#Here is the New Data frame which one is Perfectly Balanced Fraud and True Transaction

New_df

Time        V1        V2        V3        V4        V5        V6  \
188557  128025.0 -2.321648  2.860001 -1.971375 -1.092051  0.112224 -0.476006   
137040   81991.0  1.308293 -0.539817 -1.724242 -0.585777  0.042060 -1.659614   
215735  140195.0  2.088026 -0.152821 -1.806036  0.250694  0.322382 -0.847759   
76633    56665.0 -2.078804 -1.437552  1.361680  1.470361  2.025015 -1.048764   
88504    62168.0  1.213948  0.291719  0.273883  0.645315 -0.204001 -0.608376   
...          ...       ...       ...       ...       ...       ...       ...   
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494   
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536   
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346   
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548   
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695   

              V7        V8        V9  ...       V21       V22       V23  \
188557  0.145651  0.881203  0.842556  ...  0.245356  1.161735  0.039263   
137040  0.875004 -0.639607 -1.523202  ... -0.107197 -0.105311 -0.504746   
215735  0.285391 -0.200074  0.389907  ... -0.035711  0.015842  0.029154   
76633  -0.133129  0.132438 -0.770875  ...  0.197400 -0.255008  0.626297   
88504  -0.006611 -0.052600  0.062121  ... -0.262816 -0.733287  0.161932   
...          ...       ...       ...  ...       ...       ...       ...   
279863 -0.882850  0.697211 -2.064945  ...  0.778584 -0.319189  0.639419   
280143 -1.413170  0.248525 -1.127396  ...  0.370612  0.028234 -0.145640   
280149 -2.234739  1.210158 -0.652250  ...  0.751826  0.834108  0.190944   
281144 -2.208002  1.058733 -1.632333  ...  0.583276 -0.269209 -0.456108   
281674  0.223050 -0.068384  0.577829  ... -0.164350 -0.295135 -0.072173   

             V24       V25       V26       V27       V28  Amount  Class  
188557  0.297610 -0.263640 -0.207040  1.089701  0.674393    1.79      0  
137040 -0.039690  1.133864  1.543598 -0.182449 -0.022309  129.95      0  
215735 -0.473911  0.161292  0.576527 -0.110377 -0.095969    0.00      0  
76633  -0.311843  0.022109 -0.435365  0.023795  0.177590  161.90      0  
88504   0.027878  0.136029  0.124909 -0.007933  0.026852    1.29      0  
...          ...       ...       ...       ...       ...     ...    ...  
279863 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00      1  
280143 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76      1  
280149  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89      1  
281144 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00      1  
281674 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53      1  

[984 rows x 31 columns]

In [16]:
# For Cross Checking

New_df['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [133]:
# We are going to Seprate X and Y value for Predicition from Existing DF

X = New_df.drop(columns='Class', axis=1)
Y = New_df['Class']

In [134]:
X

Time        V1        V2        V3        V4        V5        V6  \
188557  128025.0 -2.321648  2.860001 -1.971375 -1.092051  0.112224 -0.476006   
137040   81991.0  1.308293 -0.539817 -1.724242 -0.585777  0.042060 -1.659614   
215735  140195.0  2.088026 -0.152821 -1.806036  0.250694  0.322382 -0.847759   
76633    56665.0 -2.078804 -1.437552  1.361680  1.470361  2.025015 -1.048764   
88504    62168.0  1.213948  0.291719  0.273883  0.645315 -0.204001 -0.608376   
...          ...       ...       ...       ...       ...       ...       ...   
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494   
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536   
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346   
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548   
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695   

              V7        V8        V9  ...       V20       V21       V22  \
188557  0.145651  0.881203  0.842556  ...  0.894877  0.245356  1.161735   
137040  0.875004 -0.639607 -1.523202  ... -0.354141 -0.107197 -0.105311   
215735  0.285391 -0.200074  0.389907  ... -0.322244 -0.035711  0.015842   
76633  -0.133129  0.132438 -0.770875  ...  0.931370  0.197400 -0.255008   
88504  -0.006611 -0.052600  0.062121  ... -0.127601 -0.262816 -0.733287   
...          ...       ...       ...  ...       ...       ...       ...   
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189   
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234   
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108   
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209   
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135   

             V23       V24       V25       V26       V27       V28  Amount  
188557  0.039263  0.297610 -0.263640 -0.207040  1.089701  0.674393    1.79  
137040 -0.504746 -0.039690  1.133864  1.543598 -0.182449 -0.022309  129.95  
215735  0.029154 -0.473911  0.161292  0.576527 -0.110377 -0.095969    0.00  
76633   0.626297 -0.311843  0.022109 -0.435365  0.023795  0.177590  161.90  
88504   0.161932  0.027878  0.136029  0.124909 -0.007933  0.026852    1.29  
...          ...       ...       ...       ...       ...       ...     ...  
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00  
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76  
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89  
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00  
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53  

[984 rows x 30 columns]

In [135]:
Y

188557    0
137040    0
215735    0
76633     0
88504     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [136]:
#Using Train Split Data Techniques

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.3)

In [137]:
#Using K-fold Method to Find out Best Classification Algorithm

from sklearn.model_selection import cross_val_score

cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X, Y,cv=10)

array([0.95959596, 0.98989899, 0.98989899, 0.8989899 , 0.8877551 ,
       0.91836735, 0.95918367, 0.90816327, 0.89795918, 0.84693878])

In [138]:
cross_val_score(SVC(gamma='auto'), X, Y,cv=10)

array([0.50505051, 0.50505051, 0.49494949, 0.49494949, 0.5       ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.5       ])

In [139]:
cross_val_score(RandomForestClassifier(n_estimators=20),X, Y,cv=10)

array([0.97979798, 0.97979798, 0.98989899, 0.87878788, 0.87755102,
       0.91836735, 0.90816327, 0.91836735, 0.92857143, 0.89795918])

In [140]:
#Finded the Better Algorithm wich one Predict Perfectly
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
log.fit(X_train, y_train)

LogisticRegression()

In [144]:
log.score(X_train, y_train)

0.9244186046511628

In [142]:
y_predicted =log.predict(X_test)
y_predicted

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1], dtype=int64)

In [143]:
y_test

44045     0
96341     1
160714    0
62334     0
94218     1
         ..
79883     1
108258    1
237654    0
176049    1
45203     1
Name: Class, Length: 296, dtype: int64